### ISSUE TITLE
RStudio downloads broken due to change in website

### ISSUE THREAD

**Issue by ethanwhite** [carpentriesoffline/offlinedatasci#47]
RStudio downloads appear to currently be failing due to a change to the download website.

```bash
$ offlinedatasci install rstudio /home/ethan/testods
Traceback (most recent call last):
  File "/home/ethan/miniconda3/envs/offlinedatasci/bin/offlinedatasci", line 8, in <module>
    sys.exit(cli.main())
  File "/home/ethan/miniconda3/envs/offlinedatasci/lib/python3.10/site-packages/offlinedatasci/cli.py", line 52, in main
    get_installer_functions(i, ods_dir)
  File "/home/ethan/miniconda3/envs/offlinedatasci/lib/python3.10/site-packages/offlinedatasci/cli.py", line 16, in get_installer_functions
    download_software(ods_dir, selection)
  File "/home/ethan/miniconda3/envs/offlinedatasci/lib/python3.10/site-packages/offlinedatasci/main.py", line 105, in download_software
    r_studio_download_table = soup.find_all('table')[download_table_num]
IndexError: list index out of range
```

**Comment by ethanwhite** [comment]
Fixed in a6b6a425c8285ef45a1866bf1b3e43a7361351b3
