### ISSUE TITLE
"HTTP Error 404: Not Found" when running installer

### ISSUE THREAD

**Issue by jsteyn** [carpentriesoffline/offlinedatasci#61]
```
(.venv) jannetta@Floki:/media/jannetta/WORKDRIVE/DATA/GitHub_Repositories/Carpentries/screenscrape$ offlinedatasci install all .

Destination:  R/R-4.3.1-win.exe 
Download path:  https://cran.r-project.org/bin/windows/base/R-4.3.1-win.exe
****Downloading file:  R/R-4.3.1-win.exe

Destination:  R/R-4.3.1.pkg 
Download path:  https://cran.r-project.org/bin/macosx/base/R-4.3.1.pkg
****Downloading file:  R/R-4.3.1.pkg
Traceback (most recent call last):
  File "/media/jannetta/WORKDRIVE/DATA/GitHub_Repositories/Carpentries/screenscrape/.venv/bin/offlinedatasci", line 8, in <module>
    sys.exit(cli.main())
  File "/media/jannetta/WORKDRIVE/DATA/GitHub_Repositories/Carpentries/screenscrape/.venv/lib/python3.10/site-packages/offlinedatasci/cli.py", line 53, in main
    get_installer_functions(i, ods_dir)
  File "/media/jannetta/WORKDRIVE/DATA/GitHub_Repositories/Carpentries/screenscrape/.venv/lib/python3.10/site-packages/offlinedatasci/cli.py", line 8, in get_installer_functions
    download_r(ods_dir)
  File "/media/jannetta/WORKDRIVE/DATA/GitHub_Repositories/Carpentries/screenscrape/.venv/lib/python3.10/site-packages/offlinedatasci/main.py", line 39, in download_r
    download_r_most_current_ver(latest_version_url_mac, destination_path)
  File "/media/jannetta/WORKDRIVE/DATA/GitHub_Repositories/Carpentries/screenscrape/.venv/lib/python3.10/site-packages/offlinedatasci/main.py", line 156, in download_r_most_current_ver
    urllib.request.urlretrieve(download_path, destination_path2)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by ethanwhite** [comment]
Notes on investigation into this:

* The base R source code for installing mac binaries [uses `contriburl`](https://github.com/wch/r-source/blob/50184ddc484e0b1f368c272c486bce79afd73dfa/src/library/utils/R/unix/mac.install.R#L20-L27). I can't get the construction there to work, but it can be set manually to either:
    * "https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3"
    * "https://cloud.r-project.org/bin/macosx/big-sur-arm64/contrib/4.3"
* This works in `download.packages()` and `available.packages()`, so this allows the core behavior in miniCRAN to work in base R
* However, miniCRAN's functions `pkgAvail()`, `updatePackages()`, and `makeRepo()` don't take `contriburl` as an optional argument and therefore can't pass it on to `available.packages()`
